GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/3242234324234234234324432432

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "SomeChannel"
}

###

DELETE http://localhost:3000/subscribers/213412321412241241214241

###

PATCH http://localhost:3000/subscribers/213412321412241241214241
Content-Type: application/json

{
    "name": "New Name"
}